import type { SyncRun, Operation } from '@/types';

// Helper to generate timestamps over the last 30 days
const daysAgo = (days: number, hours = 0, minutes = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

export const mockSyncRuns: SyncRun[] = [
  {
    id: 1,
    sync_id: 'a1b2c3d4-e5f6-4a1b-8c9d-0e1f2a3b4c5d',
    status: 'success',
    started_at: daysAgo(1, 10, 0),
    completed_at: daysAgo(1, 10, 0),
    total_operations: 12,
    successful_operations: 12,
    failed_operations: 0,
    duration_ms: 5234,
  },
  {
    id: 2,
    sync_id: 'e5f6g7h8-i9j0-4k1l-2m3n-4o5p6q7r8s9t',
    status: 'partial',
    started_at: daysAgo(2, 14, 30),
    completed_at: daysAgo(2, 14, 30),
    total_operations: 8,
    successful_operations: 6,
    failed_operations: 2,
    duration_ms: 8120,
  },
  {
    id: 3,
    sync_id: 'b3c4d5e6-f7g8-4h9i-0j1k-2l3m4n5o6p7q',
    status: 'success',
    started_at: daysAgo(3, 9, 15),
    completed_at: daysAgo(3, 9, 15),
    total_operations: 15,
    successful_operations: 15,
    failed_operations: 0,
    duration_ms: 6890,
  },
  {
    id: 4,
    sync_id: 'c5d6e7f8-g9h0-4i1j-2k3l-4m5n6o7p8q9r',
    status: 'failed',
    started_at: daysAgo(5, 11, 45),
    completed_at: daysAgo(5, 11, 45),
    total_operations: 10,
    successful_operations: 3,
    failed_operations: 7,
    duration_ms: 3450,
  },
  {
    id: 5,
    sync_id: 'd7e8f9g0-h1i2-4j3k-4l5m-6n7o8p9q0r1s',
    status: 'success',
    started_at: daysAgo(7, 15, 20),
    completed_at: daysAgo(7, 15, 20),
    total_operations: 20,
    successful_operations: 20,
    failed_operations: 0,
    duration_ms: 9870,
  },
  {
    id: 6,
    sync_id: 'e9f0g1h2-i3j4-4k5l-6m7n-8o9p0q1r2s3t',
    status: 'success',
    started_at: daysAgo(10, 8, 30),
    completed_at: daysAgo(10, 8, 30),
    total_operations: 7,
    successful_operations: 7,
    failed_operations: 0,
    duration_ms: 4120,
  },
  {
    id: 7,
    sync_id: 'f1g2h3i4-j5k6-4l7m-8n9o-0p1q2r3s4t5u',
    status: 'partial',
    started_at: daysAgo(12, 13, 0),
    completed_at: daysAgo(12, 13, 0),
    total_operations: 18,
    successful_operations: 16,
    failed_operations: 2,
    duration_ms: 7650,
  },
  {
    id: 8,
    sync_id: 'g3h4i5j6-k7l8-4m9n-0o1p-2q3r4s5t6u7v',
    status: 'success',
    started_at: daysAgo(15, 10, 10),
    completed_at: daysAgo(15, 10, 10),
    total_operations: 22,
    successful_operations: 22,
    failed_operations: 0,
    duration_ms: 11230,
  },
  {
    id: 9,
    sync_id: 'h5i6j7k8-l9m0-4n1o-2p3q-4r5s6t7u8v9w',
    status: 'success',
    started_at: daysAgo(18, 16, 45),
    completed_at: daysAgo(18, 16, 45),
    total_operations: 5,
    successful_operations: 5,
    failed_operations: 0,
    duration_ms: 2340,
  },
  {
    id: 10,
    sync_id: 'i7j8k9l0-m1n2-4o3p-4q5r-6s7t8u9v0w1x',
    status: 'failed',
    started_at: daysAgo(20, 12, 30),
    completed_at: daysAgo(20, 12, 30),
    total_operations: 12,
    successful_operations: 4,
    failed_operations: 8,
    duration_ms: 5120,
  },
];

export const mockOperations: Record<number, Operation[]> = {
  1: [
    {
      id: 1,
      operation_type: 'CREATE_ROLE',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'CREATE ROLE ANALYST_ROLE COMMENT = \'Data analysts with read access\';',
      status: 'success',
      execution_time_ms: 120,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 2,
      operation_type: 'GRANT',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'GRANT ROLE READ_ONLY TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 95,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 3,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.CUSTOMERS',
      sql_statement: 'GRANT SELECT ON TABLE PROD_DB.PUBLIC.CUSTOMERS TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 145,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 4,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.ORDERS',
      sql_statement: 'GRANT SELECT ON TABLE PROD_DB.PUBLIC.ORDERS TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 132,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 5,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_WH',
      sql_statement: 'GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 98,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 6,
      operation_type: 'CREATE_ROLE',
      target_object: 'ENGINEER_ROLE',
      sql_statement: 'CREATE ROLE ENGINEER_ROLE COMMENT = \'Engineers with write access\';',
      status: 'success',
      execution_time_ms: 115,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 7,
      operation_type: 'GRANT',
      target_object: 'ENGINEER_ROLE',
      sql_statement: 'GRANT ROLE ANALYST_ROLE TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 88,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 8,
      operation_type: 'GRANT',
      target_object: 'DEV_DB.PUBLIC',
      sql_statement: 'GRANT CREATE TABLE ON SCHEMA DEV_DB.PUBLIC TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 156,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 9,
      operation_type: 'GRANT',
      target_object: 'DEV_DB.PUBLIC.EVENTS',
      sql_statement: 'GRANT INSERT ON TABLE DEV_DB.PUBLIC.EVENTS TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 142,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 10,
      operation_type: 'GRANT',
      target_object: 'DEV_DB.PUBLIC.EVENTS',
      sql_statement: 'GRANT UPDATE ON TABLE DEV_DB.PUBLIC.EVENTS TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 138,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 11,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 105,
      executed_at: daysAgo(1, 10, 0),
    },
    {
      id: 12,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 112,
      executed_at: daysAgo(1, 10, 0),
    },
  ],
  2: [
    {
      id: 13,
      operation_type: 'CREATE_ROLE',
      target_object: 'DATA_SCIENTIST_ROLE',
      sql_statement: 'CREATE ROLE DATA_SCIENTIST_ROLE COMMENT = \'Data scientists with ML access\';',
      status: 'success',
      execution_time_ms: 128,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 14,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_DB.PUBLIC.USER_METRICS',
      sql_statement: 'GRANT SELECT ON TABLE ANALYTICS_DB.PUBLIC.USER_METRICS TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 165,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 15,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_DB.PUBLIC.REVENUE_REPORTS',
      sql_statement: 'GRANT SELECT ON TABLE ANALYTICS_DB.PUBLIC.REVENUE_REPORTS TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'failed',
      error_message: 'Table ANALYTICS_DB.PUBLIC.REVENUE_REPORTS does not exist',
      execution_time_ms: 89,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 16,
      operation_type: 'GRANT',
      target_object: 'SANDBOX_DB',
      sql_statement: 'GRANT USAGE ON DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 176,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 17,
      operation_type: 'GRANT',
      target_object: 'SANDBOX_DB.PUBLIC',
      sql_statement: 'GRANT ALL ON SCHEMA SANDBOX_DB.PUBLIC TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 198,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 18,
      operation_type: 'GRANT',
      target_object: 'ETL_WH',
      sql_statement: 'GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 102,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 19,
      operation_type: 'GRANT',
      target_object: 'ETL_WH',
      sql_statement: 'GRANT MONITOR ON WAREHOUSE ETL_WH TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'failed',
      error_message: 'Insufficient privileges to grant MONITOR on warehouse ETL_WH',
      execution_time_ms: 78,
      executed_at: daysAgo(2, 14, 30),
    },
    {
      id: 20,
      operation_type: 'REVOKE',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'REVOKE ROLE ANALYST_ROLE FROM ROLE OLD_ANALYST;',
      status: 'success',
      execution_time_ms: 125,
      executed_at: daysAgo(2, 14, 30),
    },
  ],
  3: [
    {
      id: 21,
      operation_type: 'CREATE_ROLE',
      target_object: 'ADMIN_ROLE',
      sql_statement: 'CREATE ROLE ADMIN_ROLE COMMENT = \'System administrators\';',
      status: 'success',
      execution_time_ms: 118,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 22,
      operation_type: 'GRANT',
      target_object: 'ADMIN_ROLE',
      sql_statement: 'GRANT ROLE ENGINEER_ROLE TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 92,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 23,
      operation_type: 'GRANT',
      target_object: 'ADMIN_ROLE',
      sql_statement: 'GRANT ROLE DATA_SCIENTIST_ROLE TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 87,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 24,
      operation_type: 'GRANT',
      target_object: 'PROD_DB',
      sql_statement: 'GRANT ALL ON DATABASE PROD_DB TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 215,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 25,
      operation_type: 'GRANT',
      target_object: 'DEV_DB',
      sql_statement: 'GRANT ALL ON DATABASE DEV_DB TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 198,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 26,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_DB',
      sql_statement: 'GRANT ALL ON DATABASE ANALYTICS_DB TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 203,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 27,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 145,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 28,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_WH',
      sql_statement: 'GRANT ALL ON WAREHOUSE ANALYTICS_WH TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 152,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 29,
      operation_type: 'GRANT',
      target_object: 'ETL_WH',
      sql_statement: 'GRANT ALL ON WAREHOUSE ETL_WH TO ROLE ADMIN_ROLE;',
      status: 'success',
      execution_time_ms: 148,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 30,
      operation_type: 'CREATE_ROLE',
      target_object: 'READ_ONLY',
      sql_statement: 'CREATE ROLE READ_ONLY COMMENT = \'Read-only access to production\';',
      status: 'success',
      execution_time_ms: 112,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 31,
      operation_type: 'GRANT',
      target_object: 'PROD_DB',
      sql_statement: 'GRANT USAGE ON DATABASE PROD_DB TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 134,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 32,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC',
      sql_statement: 'GRANT USAGE ON SCHEMA PROD_DB.PUBLIC TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 127,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 33,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC',
      sql_statement: 'GRANT SELECT ON ALL TABLES IN SCHEMA PROD_DB.PUBLIC TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 189,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 34,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_WH',
      sql_statement: 'GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 96,
      executed_at: daysAgo(3, 9, 15),
    },
    {
      id: 35,
      operation_type: 'CREATE_ROLE',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'CREATE ROLE DATA_ENGINEER_ROLE COMMENT = \'Data engineers for ETL pipelines\';',
      status: 'success',
      execution_time_ms: 124,
      executed_at: daysAgo(3, 9, 15),
    },
  ],
  4: [
    {
      id: 36,
      operation_type: 'GRANT',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'GRANT ROLE ENGINEER_ROLE TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 95,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 37,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.RAW',
      sql_statement: 'GRANT ALL ON SCHEMA PROD_DB.RAW TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Schema PROD_DB.RAW does not exist',
      execution_time_ms: 76,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 38,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.STAGING',
      sql_statement: 'GRANT ALL ON SCHEMA PROD_DB.STAGING TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Schema PROD_DB.STAGING does not exist',
      execution_time_ms: 72,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 39,
      operation_type: 'GRANT',
      target_object: 'ETL_WH',
      sql_statement: 'GRANT ALL ON WAREHOUSE ETL_WH TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Insufficient privileges to grant ALL on warehouse ETL_WH',
      execution_time_ms: 68,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 40,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.LOGS',
      sql_statement: 'GRANT INSERT ON TABLE PROD_DB.PUBLIC.LOGS TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 142,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 41,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.LOGS',
      sql_statement: 'GRANT UPDATE ON TABLE PROD_DB.PUBLIC.LOGS TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 138,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 42,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.LOGS',
      sql_statement: 'GRANT DELETE ON TABLE PROD_DB.PUBLIC.LOGS TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Insufficient privileges to grant DELETE on table PROD_DB.PUBLIC.LOGS',
      execution_time_ms: 64,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 43,
      operation_type: 'CREATE_ROLE',
      target_object: 'ANALYTICS_VIEWER',
      sql_statement: 'CREATE ROLE ANALYTICS_VIEWER COMMENT = \'Viewers for analytics dashboards\';',
      status: 'failed',
      error_message: 'Role name exceeds maximum length',
      execution_time_ms: 58,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 44,
      operation_type: 'REVOKE',
      target_object: 'OLD_ADMIN',
      sql_statement: 'REVOKE ROLE ADMIN_ROLE FROM ROLE OLD_ADMIN;',
      status: 'failed',
      error_message: 'Role OLD_ADMIN does not exist',
      execution_time_ms: 54,
      executed_at: daysAgo(5, 11, 45),
    },
    {
      id: 45,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT MONITOR ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Warehouse COMPUTE_WH is suspended',
      execution_time_ms: 62,
      executed_at: daysAgo(5, 11, 45),
    },
  ],
  5: [
    {
      id: 46,
      operation_type: 'CREATE_ROLE',
      target_object: 'DBA_ROLE',
      sql_statement: 'CREATE ROLE DBA_ROLE COMMENT = \'Database administrators\';',
      status: 'success',
      execution_time_ms: 122,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 47,
      operation_type: 'GRANT',
      target_object: 'DBA_ROLE',
      sql_statement: 'GRANT ROLE ADMIN_ROLE TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 89,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 48,
      operation_type: 'GRANT',
      target_object: 'PROD_DB',
      sql_statement: 'GRANT OWNERSHIP ON DATABASE PROD_DB TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 245,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 49,
      operation_type: 'GRANT',
      target_object: 'DEV_DB',
      sql_statement: 'GRANT OWNERSHIP ON DATABASE DEV_DB TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 238,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 50,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_DB',
      sql_statement: 'GRANT OWNERSHIP ON DATABASE ANALYTICS_DB TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 242,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 51,
      operation_type: 'GRANT',
      target_object: 'SANDBOX_DB',
      sql_statement: 'GRANT OWNERSHIP ON DATABASE SANDBOX_DB TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 235,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 52,
      operation_type: 'GRANT',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_DB.PUBLIC TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 178,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 53,
      operation_type: 'GRANT',
      target_object: 'ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE VIEW ON SCHEMA DEV_DB.PUBLIC TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 156,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 54,
      operation_type: 'GRANT',
      target_object: 'DATA_SCIENTIST_ROLE',
      sql_statement: 'GRANT CREATE FUNCTION ON SCHEMA SANDBOX_DB.PUBLIC TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 165,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 55,
      operation_type: 'REVOKE',
      target_object: 'DEPRECATED_ROLE',
      sql_statement: 'REVOKE ALL PRIVILEGES ON DATABASE PROD_DB FROM ROLE DEPRECATED_ROLE;',
      status: 'success',
      execution_time_ms: 187,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 56,
      operation_type: 'GRANT',
      target_object: 'READ_ONLY',
      sql_statement: 'GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_DB.PUBLIC TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 195,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 57,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.CUSTOMERS',
      sql_statement: 'GRANT REFERENCES ON TABLE PROD_DB.PUBLIC.CUSTOMERS TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 142,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 58,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC.ORDERS',
      sql_statement: 'GRANT TRUNCATE ON TABLE PROD_DB.PUBLIC.ORDERS TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 148,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 59,
      operation_type: 'CREATE_ROLE',
      target_object: 'BILLING_VIEWER',
      sql_statement: 'CREATE ROLE BILLING_VIEWER COMMENT = \'Access to billing and usage data\';',
      status: 'success',
      execution_time_ms: 119,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 60,
      operation_type: 'GRANT',
      target_object: 'BILLING_VIEWER',
      sql_statement: 'GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE BILLING_VIEWER;',
      status: 'success',
      execution_time_ms: 176,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 61,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT MODIFY ON WAREHOUSE COMPUTE_WH TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 134,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 62,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_WH',
      sql_statement: 'GRANT MODIFY ON WAREHOUSE ANALYTICS_WH TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 138,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 63,
      operation_type: 'GRANT',
      target_object: 'ETL_WH',
      sql_statement: 'GRANT MODIFY ON WAREHOUSE ETL_WH TO ROLE DBA_ROLE;',
      status: 'success',
      execution_time_ms: 142,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 64,
      operation_type: 'GRANT',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA ANALYTICS_DB.PUBLIC TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 184,
      executed_at: daysAgo(7, 15, 20),
    },
    {
      id: 65,
      operation_type: 'REVOKE',
      target_object: 'TEMP_ANALYST',
      sql_statement: 'REVOKE ROLE ANALYST_ROLE FROM ROLE TEMP_ANALYST;',
      status: 'success',
      execution_time_ms: 112,
      executed_at: daysAgo(7, 15, 20),
    },
  ],
  // Additional sync runs with fewer operations
  6: [
    {
      id: 66,
      operation_type: 'GRANT',
      target_object: 'ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE STAGE ON SCHEMA DEV_DB.PUBLIC TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 162,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 67,
      operation_type: 'GRANT',
      target_object: 'ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE FILE FORMAT ON SCHEMA DEV_DB.PUBLIC TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 159,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 68,
      operation_type: 'GRANT',
      target_object: 'DATA_SCIENTIST_ROLE',
      sql_statement: 'GRANT CREATE PROCEDURE ON SCHEMA SANDBOX_DB.PUBLIC TO ROLE DATA_SCIENTIST_ROLE;',
      status: 'success',
      execution_time_ms: 168,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 69,
      operation_type: 'GRANT',
      target_object: 'ANALYTICS_DB.PUBLIC.USER_METRICS',
      sql_statement: 'GRANT SELECT ON TABLE ANALYTICS_DB.PUBLIC.USER_METRICS TO ROLE READ_ONLY;',
      status: 'success',
      execution_time_ms: 145,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 70,
      operation_type: 'REVOKE',
      target_object: 'OLD_ENGINEER',
      sql_statement: 'REVOKE ROLE ENGINEER_ROLE FROM ROLE OLD_ENGINEER;',
      status: 'success',
      execution_time_ms: 118,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 71,
      operation_type: 'GRANT',
      target_object: 'DEV_DB.PUBLIC.EVENTS',
      sql_statement: 'GRANT DELETE ON TABLE DEV_DB.PUBLIC.EVENTS TO ROLE ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 135,
      executed_at: daysAgo(10, 8, 30),
    },
    {
      id: 72,
      operation_type: 'GRANT',
      target_object: 'BILLING_VIEWER',
      sql_statement: 'GRANT MONITOR ON ACCOUNT TO ROLE BILLING_VIEWER;',
      status: 'success',
      execution_time_ms: 172,
      executed_at: daysAgo(10, 8, 30),
    },
  ],
  7: [
    {
      id: 73,
      operation_type: 'CREATE_ROLE',
      target_object: 'SECURITY_ADMIN',
      sql_statement: 'CREATE ROLE SECURITY_ADMIN COMMENT = \'Security administrators\';',
      status: 'success',
      execution_time_ms: 126,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 74,
      operation_type: 'GRANT',
      target_object: 'SECURITY_ADMIN',
      sql_statement: 'GRANT ROLE DBA_ROLE TO ROLE SECURITY_ADMIN;',
      status: 'success',
      execution_time_ms: 92,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 75,
      operation_type: 'GRANT',
      target_object: 'SECURITY_ADMIN',
      sql_statement: 'GRANT CREATE USER ON ACCOUNT TO ROLE SECURITY_ADMIN;',
      status: 'failed',
      error_message: 'Insufficient privileges to grant CREATE USER',
      execution_time_ms: 67,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 76,
      operation_type: 'GRANT',
      target_object: 'SECURITY_ADMIN',
      sql_statement: 'GRANT CREATE ROLE ON ACCOUNT TO ROLE SECURITY_ADMIN;',
      status: 'success',
      execution_time_ms: 184,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 77,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC',
      sql_statement: 'GRANT CREATE MASKING POLICY ON SCHEMA PROD_DB.PUBLIC TO ROLE SECURITY_ADMIN;',
      status: 'success',
      execution_time_ms: 175,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 78,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC',
      sql_statement: 'GRANT CREATE ROW ACCESS POLICY ON SCHEMA PROD_DB.PUBLIC TO ROLE SECURITY_ADMIN;',
      status: 'success',
      execution_time_ms: 178,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 79,
      operation_type: 'CREATE_ROLE',
      target_object: 'COMPLIANCE_VIEWER',
      sql_statement: 'CREATE ROLE COMPLIANCE_VIEWER COMMENT = \'Compliance auditors\';',
      status: 'success',
      execution_time_ms: 121,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 80,
      operation_type: 'GRANT',
      target_object: 'COMPLIANCE_VIEWER',
      sql_statement: 'GRANT ROLE READ_ONLY TO ROLE COMPLIANCE_VIEWER;',
      status: 'success',
      execution_time_ms: 88,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 81,
      operation_type: 'GRANT',
      target_object: 'COMPLIANCE_VIEWER',
      sql_statement: 'GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE COMPLIANCE_VIEWER;',
      status: 'success',
      execution_time_ms: 169,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 82,
      operation_type: 'GRANT',
      target_object: 'ANALYST_ROLE',
      sql_statement: 'GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA ANALYTICS_DB.PUBLIC TO ROLE ANALYST_ROLE;',
      status: 'success',
      execution_time_ms: 192,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 83,
      operation_type: 'REVOKE',
      target_object: 'DEPRECATED_VIEWER',
      sql_statement: 'REVOKE ROLE READ_ONLY FROM ROLE DEPRECATED_VIEWER;',
      status: 'success',
      execution_time_ms: 115,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 84,
      operation_type: 'GRANT',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE PIPE ON SCHEMA PROD_DB.PUBLIC TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 164,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 85,
      operation_type: 'GRANT',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE STREAM ON SCHEMA PROD_DB.PUBLIC TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 161,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 86,
      operation_type: 'GRANT',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'GRANT CREATE TASK ON SCHEMA PROD_DB.PUBLIC TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 167,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 87,
      operation_type: 'GRANT',
      target_object: 'DATA_ENGINEER_ROLE',
      sql_statement: 'GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_ENGINEER_ROLE;',
      status: 'failed',
      error_message: 'Insufficient privileges to grant EXECUTE TASK',
      execution_time_ms: 71,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 88,
      operation_type: 'GRANT',
      target_object: 'COMPUTE_WH',
      sql_statement: 'GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPLIANCE_VIEWER;',
      status: 'success',
      execution_time_ms: 98,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 89,
      operation_type: 'GRANT',
      target_object: 'PROD_DB.PUBLIC',
      sql_statement: 'GRANT CREATE SEQUENCE ON SCHEMA PROD_DB.PUBLIC TO ROLE DATA_ENGINEER_ROLE;',
      status: 'success',
      execution_time_ms: 158,
      executed_at: daysAgo(12, 13, 0),
    },
    {
      id: 90,
      operation_type: 'REVOKE',
      target_object: 'TEST_ROLE',
      sql_statement: 'REVOKE ALL PRIVILEGES ON SCHEMA DEV_DB.PUBLIC FROM ROLE TEST_ROLE;',
      status: 'success',
      execution_time_ms: 176,
      executed_at: daysAgo(12, 13, 0),
    },
  ],
};

// Helper to get all operations
export const getAllMockOperations = (): Operation[] => {
  return Object.values(mockOperations).flat();
};

// Helper to get operations for a sync run
export const getMockOperationsForSync = (syncId: number): Operation[] => {
  return mockOperations[syncId] || [];
};
